name: Recovery Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Device Tree
        run: |
          mkdir -p device/tecno/camon30pro
          mv Android.mk AndroidProducts.mk BoardConfig.mk device_camon30pro.mk omni_camon30pro.mk recovery.fstab dtb.img device/tecno/camon30pro/
          [ -f kernel ] && mv kernel device/tecno/camon30pro/

      - name: Sync Minimal Manifest
        run: |
          mkdir ~/twrp
          cd ~/twrp
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-12.1
          repo sync -j$(nproc)
          cp -r $GITHUB_WORKSPACE/device ~/twrp/

      - name: Build Recovery
        run: |
          cd ~/twrp
          export ALLOW_MISSING_DEPENDENCIES=true
          . build/envsetup.sh
          lunch omni_camon30pro-eng
          make recoveryimage -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-Camon30Pro
          path: ~/twrp/out/target/product/camon30pro/recovery.img

          
