name: Recovery Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: Setup Device Tree
        run: |
          mkdir -p device/tecno/camon30pro
          mv Android.mk AndroidProducts.mk BoardConfig.mk omni_camon30pro.mk recovery.fstab dtb.img device/tecno/camon30pro/

      - name: Sync Minimal Manifest
        run: |
          mkdir ~/twrp
          cd ~/twrp
          git config --global user.email "gh-actions@github.com"
          git config --global user.name "GitHub Actions"
          # Ginanti natin ang URL sa mas stable na official TWRP manifest
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -c -j$(nproc) --force-sync --no-clone-bundle --no-tags
          cp -r $GITHUB_WORKSPACE/device ~/twrp/

      - name: Build Recovery
        run: |
          cd ~/twrp
          export ALLOW_MISSING_DEPENDENCIES=true
          . build/envsetup.sh
          lunch omni_camon30pro-eng
          make recoveryimage -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-Camon30Pro
          path: ~/twrp/out/target/product/camon30pro/recovery.img
